#!/bin/bash

set -euxo pipefail

echo "Running track setup script"

# Wait for the Instruqt host bootstrap to finish.
until [ -f /opt/instruqt/bootstrap/host-bootstrap-completed ]
do
    sleep 1
done

# Update package list
echo "Updating package list..."
sudo apt update

# Install Fontconfig and OpenJDK 17
echo "Installing Java..."
sudo apt install -y openjdk-17-jre fontconfig

echo "Adding Jenkins repository..."

sudo wget -O /usr/share/keyrings/jenkins-keyring.asc \
  https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
#curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io.key | sudo tee \
#  /usr/share/keyrings/jenkins-keyring.asc > /dev/null

echo "Adding Jenkins repository..."
echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/ | sudo tee /etc/apt/sources.list.d/jenkins.list > /dev/null

# Update the package index again
echo "Updating package index after adding Jenkins repository..."
sudo apt-get update

# Install Jenkins
echo "Installing Jenkins..."
sudo apt-get install -y jenkins

# Start and enable Jenkins service
echo "Starting and enabling Jenkins..."
sudo systemctl start jenkins
sudo systemctl enable jenkins

